/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/assets/models/duck/duck.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/duck.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Duck_Eyes.geometry} material={nodes.Duck_Eyes.material} />
      <mesh geometry={nodes.Duck_Beak.geometry} material={nodes.Duck_Beak.material} />
      <mesh geometry={nodes.Duck_Duck.geometry} material={nodes.Duck_Duck.material} />
      <mesh geometry={nodes.Duck_Wings.geometry} material={nodes.Duck_Wings.material} />
      <mesh geometry={nodes.Plane_Material.geometry} material={nodes.Plane_Material.material} />
    </group>
  )
}

useGLTF.preload('/duck.glb')
